### ISSUE TITLE
乱码和粘包

### ISSUE THREAD

**Issue by luomoi** [ruihanL/EasySocket#2]
接收的数据会出现粘包和乱码的想象

**Comment by ruihanL** [comment]
发送方是否有换行符

**Comment by luomoi** [comment]
有换行符，粘包自己通过代码处理了，但是接收过来的部分数据有乱码




------------------ 原始邮件 ------------------
发件人: "ruihanL"<notifications@github.com>;
发送时间: 2019年6月24日(星期一) 下午4:30
收件人: "ruihanL/EasySocket"<EasySocket@noreply.github.com>;
抄送: "851698148"<851698148@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ruihanL/EasySocket] 乱码和粘包 (#2)



发送方是否有换行符

**Comment by ruihanL** [comment]
哦，我这边再看看

**Comment by sceneren** [comment]
乱码问题解决了吗？
