### ISSUE TITLE
能不能发数据把后面的回车去掉

### ISSUE THREAD

**Issue by TsaiYongChuan** [ruihanL/EasySocket#3]
因为回车会影响我的数据结构，导致被服务器不识别

**Comment by TsaiYongChuan** [comment]
别人搭建的服务器

**Comment by ruihanL** [comment]
这个这边修复一下

**Comment by TsaiYongChuan** [comment]
> 这个这边修复一下

大佬大概多久能修复

**Comment by ruihanL** [comment]
我检查了下，发送数据本身没有回车的，发送数据是任意字节的。

只有示例的服务器里面，有个readline()会有个接收换行的阻塞而已。

**Comment by TsaiYongChuan** [comment]
那如果我想正常的使用，要做什么吗




------------------ 原始邮件 ------------------
发件人: "ruihanL"<notifications@github.com>;
发送时间: 2019年7月9日(星期二) 中午11:30
收件人: "ruihanL/EasySocket"<EasySocket@noreply.github.com>;
抄送: "永川"<373275869@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ruihanL/EasySocket] 能不能发数据把后面的回车去掉 (#3)



我检查了下，发送数据本身没有回车的，发送数据是任意字节的。 
 
 只有示例的服务器里面，有个readline()会有个接收换行的阻塞而已。

**Comment by ruihanL** [comment]
Android端只需要正常集成，就可以收到服务器发送过来的数据，也可以发数据回去，你可以参考下代码里面那个App示例。

**Comment by TsaiYongChuan** [comment]
我就是参考你的demo，在上面修改了ip和端口，然后开始发送数据，会存在发送失败的问题




------------------ 原始邮件 ------------------
发件人: "ruihanL"<notifications@github.com>;
发送时间: 2019年7月9日(星期二) 下午2:38
收件人: "ruihanL/EasySocket"<EasySocket@noreply.github.com>;
抄送: "永川"<373275869@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ruihanL/EasySocket] 能不能发数据把后面的回车去掉 (#3)



Android端只需要正常集成，就可以收到服务器发送过来的数据，也可以发数据回去，你可以参考下代码里面那个App示例。

**Comment by ruihanL** [comment]
你再检查检查，看看是否是服务器问题

**Comment by TsaiYongChuan** [comment]
谢谢，后面可以了




------------------ 原始邮件 ------------------
发件人: "ruihanL"<notifications@github.com>;
发送时间: 2019年7月10日(星期三) 中午12:38
收件人: "ruihanL/EasySocket"<EasySocket@noreply.github.com>;
抄送: "永川"<373275869@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ruihanL/EasySocket] 能不能发数据把后面的回车去掉 (#3)




你再检查检查，看看是否是服务器问题
