### ISSUE TITLE
server端断开  其实mSocket.isConnected()  这个方法是判断出不来连接断开的

### ISSUE THREAD

**Issue by zjianflys** [ruihanL/EasySocket#7]
作者有其他的解决方案嘛   我之前的解决方案是 在写入的时候判断重连,只有在写入的数据的时候 会报错  然后就重连

**Comment by ruihanL** [comment]
可以捕获异常，出现异常的时候重连



---原始邮件---
发件人: "飞飞"<notifications@github.com&gt;
发送时间: 2019年8月29日(星期四) 下午3:08
收件人: "ruihanL/EasySocket"<EasySocket@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [ruihanL/EasySocket] server端断开  其实mSocket.isConnected()  这个方法是判断出不来连接断开的 (#7)



作者有其他的解决方案嘛   我之前的解决方案是 在写入的时候判断重连,只有在写入的数据的时候 会报错  然后就重连

**Comment by zjianflys** [comment]
我用网络调试助手试,就会出现这个问题  
 ` if (socket.isConnected) {
                    socket.send((etSend.getText().toString()).getBytes());
                }`

我把服务断开之后 还是会进if

**Comment by ruihanL** [comment]
你用发送异常或者接收异常来判断



---原始邮件---
发件人: "飞飞"<notifications@github.com&gt;
发送时间: 2019年8月29日(星期四) 下午4:18
收件人: "ruihanL/EasySocket"<EasySocket@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"ruihanL"<1119124773@qq.com&gt;;
主题: Re: [ruihanL/EasySocket] server端断开  其实mSocket.isConnected()  这个方法是判断出不来连接断开的 (#7)



我用网络调试助手试,就会出现这个问题
  if (socket.isConnected) { socket.send((etSend.getText().toString()).getBytes()); }
 
我把服务断开之后 还是会进if

**Comment by zjianflys** [comment]
en   谢谢
